import Index from "./index";
import Footer from "../components/Footer";
import nightsky from "../assests/nightsky.jpg";
import Image from 'next/image'
import Head from "next/head";
import Link from "next/link";

export default function About(props) {
  const lastepisode = props.episodes.slice(-5).reverse();
  return (
    <>
      <Index />
      <Head>
        <title>Privacy</title>
        <link rel="shortcut icon" href="/saghiomey.ico" />
      </Head>
      <div className="relative">
        <Image className="bg-cover xl:w-full" src={nightsky} alt="nightsky" />
        <div className="absolute grid justify-items-center top-8 md:top-28 w-full text-white">
          <span className="text-lg md:text-5xl font-sans font-bold">Privacy</span>
          <span className="text-sm md:text-xl md:mt-1 font-sans font-bold">Last Updated: September 6, 2023</span>
        </div>
        <div className="absolute text-center -top-12 md:top-16 lg:top-2/4 mt-32 w-full min-h-max bg-black">
          <div className="lg:mb-56 mt-12 lg:ml-20 leading-8 text-gray-200">
            <span className="text-xl md:text-2xl text-gray-400 font-sans font-bold">
            This privacy notice for <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> (doing business as <span className="text-xl md:text-2xl font-sans font-bold text-white">SM</span>) (“Company,” “we,” “us,” or “our“), describes how and why we might collect, store, use, and/or share (“process“) your information when you use our services (“Services“), such as when you:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span> Visit our website at <span className="text-xl md:text-2xl font-sans font-bold text-white">https://saghiomey.netlify.app</span>, or any website of ours that links to this privacy notice.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span> Engage with us in other related ways ― including any sales, marketing, or events.<br /><br /><br />  
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Questions or concerns?</span> Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have any questions or concerns, please contact us at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link>.<br/><br/><br/>
            This privacy policy was created by <Link className="text-xl md:text-2xl font-sans font-bold text-white" href="https://www.linkedin.com/in/mohammadreza-khorrami-238302215/">Milad</Link><br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">SUMMARY OF KEY POINTS</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">This summary provides key points from our privacy notice, but you can find out more details about any of these topics by using our table of contents below to find the section you are looking for.</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">What personal information do we process?</span> When you visit, use, or navigate our Services, we may process personal information depending on how you interact with <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> and the Services, the choices you make, and the products and features you use.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Do we process any sensitive personal information?</span> We do not process sensitive personal information.<br /><br /><br /> 
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Do you receive any information from third parties?</span> We may receive information from public databases, marketing partners, social media platforms, and other outside sources.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">How do you process my information?</span> We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so.<br /><br /><br /> 
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In what situations and with which types of parties do we share personal information?</span> We may share information in specific situations and with specific categories of third parties.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">How do we keep your information safe?</span> We have organizational and technical processes and procedures in place to protect your personal information. However, no electronic transmission over the internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">What are your rights?</span> Depending on where you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">How do I exercise my rights?</span> The easiest way to exercise your rights is by contacting us. We will consider and act upon any request in accordance with applicable data protection laws.<br /><br /><br />
            Want to learn more about what <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> does with any information we collect? Review the notice in full below.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">TABLE OF CONTENTS</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1. WHAT INFORMATION DO WE COLLECT?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2. HOW DO WE PROCESS YOUR INFORMATION?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3. WHAT LEGAL BASES DO WE RELY ON TO PROCESS YOUR PERSONAL INFORMATION?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">5. WHAT IS OUR STANCE ON THIRD-PARTY WEBSITES?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">6. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">7. HOW DO WE HANDLE YOUR SOCIAL LOGINS?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">8. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">9. HOW LONG DO WE KEEP YOUR INFORMATION?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">10. HOW DO WE KEEP YOUR INFORMATION SAFE?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">11. DO WE COLLECT INFORMATION FROM MINORS?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">12. WHAT ARE YOUR PRIVACY RIGHTS?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">13. CONTROLS FOR DO-NOT-TRACK FEATURES</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">14. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">15. DO VIRGINIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">16. DO WE MAKE UPDATES TO THIS NOTICE?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">17. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">18. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</span><br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">1. WHAT INFORMATION DO WE COLLECT?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Personal information you disclose to us</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We collect personal information that you provide to us.<br /><br /><br />
            We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Personal Information Provided by You. </span>The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make, and the products and features you use. The personal information we collect may include the following:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Email<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Recorded Voice<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>Photo Cover(just request from guests)<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Sensitive Information. </span>We do not process sensitive information.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Social Media Login Data. </span>We may provide you with the option to register with us using your existing social media account details, like your Facebook, Twitter, or other social media account. If you choose to register in this way, we will collect the information described in the section called “HOW DO WE HANDLE YOUR SOCIAL LOGINS?” below.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Geolocation Information. We may request access or permission to track location-based information from your mobile device, either continuously or while you are using our mobile application(s), to provide certain location-based services. If you wish to change our access or permissions, you may do so in your device’s settings.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Mobile Device Access. We may request access or permission to certain features from your mobile device, including your mobile device’s bluetooth, calendar, camera, own, and other features. If you wish to change our access or permissions, you may do so in your device’s settings.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>Mobile Device Data. We automatically collect device information (such as your mobile device ID, model, and manufacturer), operating system, version information and system configuration information, device and application identification numbers, browser type and version, hardware model Internet service provider and/or mobile carrier, and Internet Protocol (IP) address (or proxy server). If you are using our application(s), we may also collect information about the phone network associated with your mobile device, your mobile device’s operating system or platform, the type of mobile device you use, your mobile device’s unique device ID, and information about the features of our application(s) you accessed.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>Push Notifications. We may request to send you push notifications regarding your account or certain features of the application(s). If you wish to opt out from receiving these types of communications, you may turn them off in your device’s settings.<br /><br /><br />
            This information is primarily needed to maintain the security and operation of our application(s), for troubleshooting, and for our internal analytics and reporting purposes.<br /><br /><br />
            All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Information automatically collected</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>Some information — such as your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our Services.<br /><br /><br />
            We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information. This information is primarily needed to maintain the security and operation of our Services, and for our internal analytics and reporting purposes.<br /><br /><br />
            Like many businesses, we also collect information through cookies and similar technologies.<br /><br /><br />
            The information we collect includes:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Log and Usage Data. Log and usage data is service-related, diagnostic, usage, and performance information our servers automatically collect when you access or use our Services and which we record in log files. Depending on how you interact with us, this log data may include your IP address, device information, browser type, and settings and information about your activity in the Services (such as the date/time stamps associated with your usage, pages and files viewed, searches, and other actions you take such as which features you use), device event information (such as system activity, error reports (sometimes called “crash dumps”), and hardware settings).<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Device Data. We collect device data such as information about your computer, phone, tablet, or other device you use to access the Services. Depending on the device used, this device data may include information such as your IP address (or proxy server), device and application identification numbers, location, browser type, hardware model, Internet service provider and/or mobile carrier, operating system, and system configuration information.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>Location Data. We collect location data such as information about your device’s location, which can be either precise or imprecise. How much information we collect depends on the type and settings of the device you use to access the Services. For example, we may use GPS and other technologies to collect geolocation data that tells us your current location (based on your IP address). You can opt out of allowing us to collect this information either by refusing access to the information or by disabling your Location setting on your device. However, if you choose to opt out, you may not be able to use certain aspects of the Services.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Information collected from other sources</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We may collect limited data from public databases, marketing partners, social media platforms, and other outside sources.<br /><br /><br />
            In order to enhance our ability to provide relevant marketing, offers, and services to you and update our records, we may obtain information about you from other sources, such as public databases, joint marketing partners, affiliate programs, data providers, social media platforms, and from other third parties. This information includes mailing addresses, job titles, email addresses, phone numbers, intent data (or user behavior data), Internet Protocol (IP) addresses, social media profiles, social media URLs, and custom profiles, for purposes of targeted advertising and event promotion. If you interact with us on a social media platform using your social media account (e.g., Facebook or Twitter), we receive personal information about you such as your name, email address, and gender. Any personal information that we collect from your social media account depends on your social media account’s privacy settings.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">HOW DO WE PROCESS YOUR INFORMATION?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">We process your personal information for a variety of reasons, depending on how you interact with our Services, including:</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To facilitate account creation and authentication and otherwise manage user accounts. </span>We may process your information so you can create and log in to your account, as well as keep your account in working order.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To deliver and facilitate delivery of services to the user. </span>We may process your information to provide you with the requested service.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To respond to user inquiries/offer support to users. </span>We may process your information to respond to your inquiries and solve any potential issues you might have with the requested service.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To send administrative information to you. </span>We may process your information to send you details about our products and services, changes to our terms and policies, and other similar information.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To fulfill and manage your orders. </span>We may process your information to fulfill and manage your orders, payments, returns, and exchanges made through the Services.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To enable user-to-user communications. </span>We may process your information if you choose to use any of our offerings that allow for communication with another user.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To request feedback. </span>We may process your information when necessary to request feedback and to contact you about your use of our Services.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To send you marketing and promotional communications. </span>We may process the personal information you send to us for our marketing purposes, if this is in accordance with your marketing preferences. You can opt out of our marketing emails at any time.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To deliver targeted advertising to you. </span>We may process your information to develop and display personalized content and advertising tailored to your interests, location, and more.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To protect our Services. </span>We may process your information as part of our efforts to keep our Services safe and secure, including fraud monitoring and prevention.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To identify usage trends. </span>We may process information about how you use our Services to better understand how they are being used so we can improve them.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To determine the effectiveness of our marketing and promotional campaigns. </span>We may process your information to better understand how to provide marketing and promotional campaigns that are most relevant to you.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">To save or protect an individual’s vital interest. </span>We may process your information when necessary to save or protect an individual’s vital interest, such as to prevent harm.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">3. WHAT LEGAL BASES DO WE RELY ON TO PROCESS YOUR INFORMATION?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We only process your personal information when we believe it is necessary and we have a valid legal reason (i.e., legal basis) to do so under applicable law, like with your consent, to comply with laws, to provide you with services to enter into or fulfill our contractual obligations, to protect your rights, or to fulfill our legitimate business interests.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">If you are located in the EU or UK, this section applies to you.</span><br /><br /><br />
            The General Data Protection Regulation (GDPR) and UK GDPR require us to explain the valid legal bases we rely on in order to process your personal information. As such, we may rely on the following legal bases to process your personal information:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Consent. </span>We may process your information if you have given us permission (i.e., consent) to use your personal information for a specific purpose. You can withdraw your consent at any time.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Performance of a Contract. </span>We may process your personal information when we believe it is necessary to fulfill our contractual obligations to you, including providing our Services or at your request prior to entering into a contract with you.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Legitimate Interests. </span>We may process your information when we believe it is reasonably necessary to achieve our legitimate business interests and those interests do not outweigh your interests and fundamental rights and freedoms. For example, we may process your personal information for some of the purposes described in order to:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Send users information about special offers and discounts on our products and services<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Develop and display personalized and relevant advertising content for our users<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>Analyze how our services are used so we can improve them to engage and retain users<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>Support our marketing activities<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">5.</span>Diagnose problems and/or prevent fraudulent activities<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">6.</span>Understand how our users use our products and services so we can improve user experience<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Legal Obligations. </span>We may process your information where we believe it is necessary for compliance with our legal obligations, such as to cooperate with a law enforcement body or regulatory agency, exercise or defend our legal rights, or disclose your information as evidence in litigation in which we are involved.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Vital Interests. </span>We may process your information where we believe it is necessary to protect your vital interests or the vital interests of a third party, such as situations involving potential threats to the safety of any person.<br /><br /><br />
            In legal terms, we are generally the “data controller” under European data protection laws of the personal information described in this privacy notice, since we determine the means and/or purposes of the data processing we perform. This privacy notice does not apply to the personal information we process as a “data processor” on behalf of our customers. In those situations, the customer that we provide services to and with whom we have entered into a data processing agreement is the “data controller” responsible for your personal information, and we merely process your information on their behalf in accordance with your instructions. If you want to know more about our customers’ privacy practices, you should read their privacy policies and direct any questions you have to them.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">If you are located in Canada, this section applies to you.</span><br /><br /><br />
            We may process your information if you have given us specific permission (i.e., express consent) to use your personal information for a specific purpose, or in situations where your permission can be inferred (i.e., implied consent). You can withdraw your consent at any time.<br /><br /><br />
            In some exceptional cases, we may be legally permitted under applicable law to process your information without your consent, including, for example:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>If collection is clearly in the interests of an individual and consent cannot be obtained in a timely way<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>For investigations and fraud detection and prevention<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>For business transactions provided certain conditions are met<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>If it is contained in a witness statement and the collection is necessary to assess, process, or settle an insurance claim<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">5.</span>For identifying injured, ill, or deceased persons and communicating with next of kin<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">6.</span>If we have reasonable grounds to believe an individual has been, is, or may be victim of financial abuse<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">7.</span>If it is reasonable to expect collection and use with consent would compromise the availability or the accuracy of the information and the collection is reasonable for purposes related to investigating a breach of an agreement or a contravention of the laws of Canada or a province<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">8.</span>If disclosure is required to comply with a subpoena, warrant, court order, or rules of the court relating to the production of records<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">9.</span>If it was produced by an individual in the course of their employment, business, or profession and the collection is consistent with the purposes for which the information was produced<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">10.</span>If the collection is solely for journalistic, artistic, or literary purposes<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">11.</span>If the information is publicly available and is specified by the regulations<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">4. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We may share information in specific situations described in this section and/or with the following categories of third parties.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Vendors, Consultants, and Other Third-Party Service Providers. </span> We may share your data with third-party vendors, service providers, contractors, or agents (“third parties”) who perform services for us or on our behalf and require access to such information to do that work. We have contracts in place with our third parties, which are designed to help safeguard your personal information. This means that they cannot do anything with your personal information unless we have instructed them to do it. They will also not share your personal information with any organization apart from us. They also commit to protect the data they hold on our behalf and to retain it for the period we instruct. The categories of third parties we may share personal information with are as follows:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Ad Networks<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Affiliate Marketing Programs<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>Cloud Computing Services<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>Communication & Collaboration Tools<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">5.</span>Data Analytics Services<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">6.</span>Data Storage Service Providers<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">7.</span>Finance & Accounting Tools<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">8.</span>Government Entities<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">9.</span>Order Fulfillment Service Providers<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">10.</span>Payment Processors<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">11.</span>Performance Monitoring Tools<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">12.</span>Product Engineering & Design Tools<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">13.</span>Retargeting Platforms<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">14.</span>Sales & Marketing Tools<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">15.</span>Social Networks<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">16.</span>Testing Tools<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">17.</span>User Account Registration & Authentication Services<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">18.</span>Website Hosting Service Providers<br /><br /><br />
            We also may need to share your personal information in the following situations:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Business Transfers.</span>We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Affiliates.</span>We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy notice. Affiliates include our parent company and any subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Business Partners.</span>We may share your information with our business partners to offer you certain products, services, or promotions.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Other Users.</span>When you share personal information (for example, by posting comments, contributions, or other content to the Services)  or otherwise interact with public areas of the Services, such personal information may be viewed by all users and may be publicly made available outside the Services in perpetuity. If you interact with other users of our Services and register for our Services through a social network (such as Facebook), your contacts on the social network will see your name, profile photo, and descriptions of your activity. Similarly, other users will be able to view descriptions of your activity, communicate with you within our Services, and view your profile.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Offer Wall.</span>Our application(s) may display a third-party hosted “offer wall.” Such an offer wall allows third-party advertisers to offer virtual currency, gifts, or other items to users in return for the acceptance and completion of an advertisement offer. Such an offer wall may appear in our application(s) and be displayed to you based on certain data, such as your geographic area or demographic information. When you click on an offer wall, you will be brought to an external website belonging to other persons and will leave our application(s). A unique identifier, such as your user ID, will be shared with the offer wall provider in order to prevent fraud and properly credit your account with the relevant reward.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">5. WHAT IS OUR STANCE ON THIRD-PARTY WEBSITES?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We are not responsible for the safety of any information that you share with third parties that we may link to or who advertise on our Services, but are not affiliated with, our Services.<br /><br /><br />
            The Services, including our offer wall, may link to third-party websites, online services, or mobile applications and/or contain advertisements from third parties that are not affiliated with us and which may link to other websites, services, or applications. Accordingly, we do not make any guarantee regarding any such third parties, and we will not be liable for any loss or damage caused by the use of such third-party websites, services, or applications. The inclusion of a link towards a third-party website, service, or application does not imply an endorsement by us. We cannot guarantee the safety and privacy of data you provide to any third parties. Any data collected by third parties is not covered by this privacy notice. We are not responsible for the content or privacy and security practices and policies of any third parties, including other websites, services, or applications that may be linked to or from the Services. You should review the policies of such third parties and contact them directly to respond to your questions.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">6. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We may use cookies and other tracking technologies to collect and store your information.<br /><br /><br />
            We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Notice.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">7. HOW DO WE HANDLE YOUR SOCIAL LOGINS?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>If you choose to register or log in to our services using a social media account, we may have access to certain information about you.<br /><br /><br />
            Our Services offer you the ability to register and log in using your third-party social media account details (like your Facebook or Twitter logins). Where you choose to do this, we will receive certain profile information about you from your social media provider. The profile information we receive may vary depending on the social media provider concerned, but will often include your name, email address, friends list, and profile picture, as well as other information you choose to make public on such a social media platform. If you log in using Facebook, we may also request access to other permissions related to your account, such as your friends, check-ins, and likes, and you may choose to grant or deny us access to each individual permission.<br /><br /><br />
            We will use the information we receive only for the purposes that are described in this privacy notice or that are otherwise made clear to you on the relevant Services. Please note that we do not control, and are not responsible for, other uses of your personal information by your third-party social media provider. We recommend that you review their privacy notice to understand how they collect, use and share your personal information, and how you can set your privacy preferences on their sites and apps.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">8. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We may transfer, store, and process your information in countries other than your own.<br /><br /><br />
            Our servers are located in Iran. If you are accessing our Services from outside Iran, please be aware that your information may be transferred to, stored, and processed by us in our facilities and by those third parties with whom we may share your personal information (see “WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?” above), and other countries.<br /><br /><br />
            If you are a resident in the European Economic Area (EEA) or United Kingdom (UK), then these countries may not necessarily have data protection laws or other similar laws as comprehensive as those in your country. However, we will take all necessary measures to protect your personal information in accordance with this privacy notice and applicable law.<br /><br /><br />
            European Commission’s Standard Contractual Clauses:<br /><br /><br />
            We have implemented measures to protect your personal information, including by using the European Commission’s Standard Contractual Clauses for transfers of personal information between our group companies and between us and our third-party providers. These clauses require all recipients to protect all personal information that they process originating from the EEA or UK in accordance with European data protection laws and regulations. We have implemented similar appropriate safeguards with our third-party service providers and partners and further details can be provided upon request.<br /><br /><br />
            Binding Corporate Rules:<br /><br /><br />
            These include a set of Binding Corporate Rules (“BCRs”) established and implemented by <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>. Our BCRs have been recognized by EEA and UK data protection authorities as providing an adequate level of protection to the personal information we process internationally.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>. adheres to and complies with the Privacy Shield Principles when processing personal information from the EU, UK, or Switzerland. If we have received your personal information in the United States and subsequently transfer that information to a third party acting as our agent, and such third party agent processes your personal information in a manner inconsistent with the Privacy Shield Principles, we will remain liable unless we can prove we are not responsible for the event giving rise to the damage.<br /><br /><br />
            With respect to personal information received or transferred pursuant to the Privacy Shield Framework, <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>. is subject to the investigatory and enforcement powers of the US Federal Trade Commission (“FTC”). In certain situations, we may be required to disclose personal information in response to lawful requests by public authorities, including to meet national security or law enforcement requirements.<br /><br /><br />
            If you have any questions or concerns relating to <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>’s Privacy Shield certification, please write to us at the contact details below. We commit to resolving any complaints or disputes about our collection and use of your personal information under the Privacy Shield.<br /><br /><br />
            In limited situations, EU, UK, and Swiss individuals may seek redress from the Privacy Shield Panel, a binding arbitration mechanism.<br /><br /><br />
            Please be sure to review the following sections of this Privacy Notice for additional details relevant to <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>’s participation in the EU-US and Swiss-US Privacy Shield:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>WHAT INFORMATION DO WE COLLECT? To learn more about the types of personal data <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> collects.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>HOW DO WE PROCESS YOUR INFORMATION? To learn more about the purposes for which <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> collects and uses personal information about you.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION? To learn more about the type or identity of third parties to which <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> discloses personal information, and the purposes for which we do so.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>WHAT ARE YOUR PRIVACY RIGHTS? <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> To learn more about the right of individuals to access their personal data.<br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">9. HOW LONG DO WE KEEP YOUR INFORMATION?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law.<br /><br /><br />
            We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than the period of time in which users have an account with us When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">10. HOW DO WE KEEP YOUR INFORMATION SAFE?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We aim to protect your personal information through a system of organizational and technical security measures.<br /><br /><br />
            We have implemented appropriate and reasonable technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Although we will do our best to protect your personal information, transmission of personal information to and from our Services is at your own risk. You should only access the Services within a secure environment.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">11. HOW DO WE KEEP YOUR INFORMATION SAFE?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>We do not knowingly collect data from or market to children under 18 years of age.<br /><br /><br />
            We do not knowingly solicit data from or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us at <span className="text-xl md:text-2xl font-sans font-bold text-white"><Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link></span><br/><br/><br/>
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">12. WHAT ARE YOUR PRIVACY RIGHTS?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>In some regions, such as the European Economic Area (EEA), United Kingdom (UK), and Canada, you have rights that allow you greater access to and control over your personal information. You may review, change, or terminate your account at any time.<br /><br /><br />
            In some regions (like the EEA, UK, and Canada), you have certain rights under applicable data protection laws. These may include the right (i) to request access and obtain a copy of your personal information, (ii) to request rectification or erasure; (iii) to restrict the processing of your personal information; and (iv) if applicable, to data portability. In certain circumstances, you may also have the right to object to the processing of your personal information. You can make such a request by contacting us by using the contact details provided in the section “HOW CAN YOU CONTACT US ABOUT THIS NOTICE?” below.<br /><br /><br />
            We will consider and act upon any request in accordance with applicable data protection laws.<br /><br /><br />
            If you are located in the EEA or UK and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: <a href="https://edpb.europa.eu/about-edpb/about-edpb/members_en"></a>.<br /><br /><br />
            If you are located in Switzerland, the contact details for the data protection authorities are available here: <a href="https://www.edoeb.admin.ch/edoeb/en/home.html"></a>.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Withdrawing your consent: </span>If we are relying on your consent to process your personal information, which may be express and/or implied consent depending on the applicable law, you have the right to withdraw your consent at any time. You can withdraw your consent at any time by contacting us by using the contact details provided in the section “HOW CAN YOU CONTACT US ABOUT THIS NOTICE?” below or updating your preferences.<br /><br /><br />
            However, please note that this will not affect the lawfulness of the processing before its withdrawal, nor when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Opting out of marketing and promotional communications: </span>You can unsubscribe from our marketing and promotional communications at any time by clicking on the unsubscribe link in the emails that we send, replying “STOP” or “UNSUBSCRIBE” to the SMS messages that we send, or by contacting us using the details provided in the section “HOW CAN YOU CONTACT US ABOUT THIS NOTICE?” below. You will then be removed from the marketing lists — however, we may still communicate with you, for example to send you service-related messages that are necessary for the administration and use of your account, to respond to service requests, or for other non-marketing purposes.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Account Information</span><br /><br /><br />
            If you would at any time like to review or change the information in your account or terminate your account, you can:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Log in to your account settings and update your user account.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Contact us using the contact information provided.<br /><br /><br />
            Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our legal terms and/or comply with applicable legal requirements.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Cookies and similar technologies: </span>Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our Services.<br /><br /><br />
            If you have questions or comments about your privacy rights, you may email us at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link><br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">13. CONTROLS FOR DO-NOT-TRACK FEATURES</span><br /><br /><br />
            Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (“DNT”) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">14. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.<br /><br /><br />
            California Civil Code Section 1798.83, also known as the “Shine The Light” law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.<br /><br /><br />
            If you are under 18 years of age, reside in California, and have a registered account with Services, you have the right to request removal of unwanted data that you publicly post on the Services. To request removal of such data, please contact us using the contact information provided below and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Services, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g., backups, etc.).<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">CCPA Privacy Notice </span><br /><br /><br />
            The California Code of Regulations defines a “resident” as:<br /><br /><br />
            (1) every individual who is in the State of California for other than a temporary or transitory purpose and<br />
            (2) every individual who is domiciled in the State of California who is outside the State of California for a temporary or transitory purpose<br /><br /><br />
            All other individuals are defined as “non-residents.”<br /><br /><br />
            If this definition of “resident” applies to you, we must adhere to certain rights and obligations regarding your personal information.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">How do we use and share your personal information?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> collects and shares your personal information through:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Targeting cookies/Marketing cookies<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Social media cookies<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>Beacons/Pixels/Tags<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>Social media plugins: We use social media features, such as a “Like” button, and widgets, such as a “Share” button in our Services. Such features may process your Internet Protocol (IP) address and track which page you are visiting on our website. We may place a cookie to enable the feature to work correctly. If you are logged in on a certain social media platform and you interact with a widget or button belonging to that social media platform, this information may be recorded to your profile of such social media platform. To avoid this, you should log out from that social media platform before accessing or using the Services. Social media features and widgets may be hosted by a third party or hosted directly on our Services. Your interactions with these features are governed by the privacy notices of the companies that provide them. By clicking on one of these buttons, you agree to the use of this plugin and consequently the transfer of personal information to the corresponding social media service. We have no control over the essence and extent of these transmitted data or their additional processing.<br /><br /><br />
            More information about our data collection and sharing practices can be found in this privacy notice<br /><br /><br />
            You can opt out from the selling or sharing of your personal information by disabling cookies in Cookie Preference Settings and clicking on the Do Not Sell or Share My Personal Information link on our homepage.<br /><br /><br />
            You may contact us by email at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link> or by referring to the contact details at the bottom of this document.<br /><br /><br />
            If you are using an authorized agent to exercise your right to opt out we may deny a request if the authorized agent does not submit proof that they have been validly authorized to act on your behalf.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Will your information be shared with anyone else?</span><br /><br /><br />
            We may disclose your personal information with our service providers pursuant to a written contract between us and each service provider. Each service provider is a for-profit entity that processes the information on our behalf, following the same strict privacy protection obligations mandated by the CCPA.<br /><br /><br />
            We may use your personal information for our own business purposes, such as for undertaking internal research for technological development and demonstration. This is not considered to be “selling” of your personal information.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> has disclosed the following categories of personal information to third parties for a business or commercial purpose in twelve (12) months:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category A.</span> Identifiers, such as contact details like your real name, alias, postal address, telephone or mobile contact number, unique personal identifier, online identifier, Internet Protocol address, email address, and account name.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category B.</span> Personal information, as defined in the California Customer Records law, such as your name, contact information, education, employment, employment history, and financial information.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category C.</span> Characteristics of protected classifications under California or federal law, such as gender or date of birth.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category D.</span> Commercial information, such as transaction information, purchase history, financial details, and payment information.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category E.</span> Biometric information, such as fingerprints and voiceprints.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category F.</span> Internet or other electronic network activity information, such as browsing history, search history, online behavior, interest data, and interactions with our and other websites, applications, systems, and advertisements.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category G.</span> Geolocation data, such as device location.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category H.</span> Audio, electronic, visual, and similar information, such as images and audio, video, or call recordings created in connection with our business activities.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category I.</span> Professional or employment-related information, such as business contact details in order to provide you our services at a business level or job title, work history, and professional qualifications if you apply for a job with us.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category J.</span> Education information, such as student records and directory information.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category K.</span> Inferences drawn from any of the personal information listed above to create a profile or summary about, for example, an individual’s preferences and characteristics.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Category L.</span> Sensitive personal information, such as account login information, drivers’ licenses, health data, precise geolocation, racial or ethnic origin, religious or philosophical beliefs, and sex life or sexual orientation.<br /><br /><br />
            The categories of third parties to whom we disclosed personal information for a business or commercial purpose can be found under “WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?“.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>has not sold or shared any personal information to third parties for a business or commercial purpose in the preceding twelve (12) months.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Your rights with respect to your personal data</span><br /><br /><br />
            Right to request deletion of the data — Request to delete<br /><br /><br />
            You can ask for the deletion of your personal information. If you ask us to delete your personal information, we will respect your request and delete your personal information, subject to certain exceptions provided by law, such as (but not limited to) the exercise by another consumer of his or her right to free speech, our compliance requirements resulting from a legal obligation, or any processing that may be required to protect against illegal activities.<br /><br /><br />
            Right to be informed — Request to know<br /><br /><br />
            Depending on the circumstances, you have a right to know:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>whether we collect and use your personal information;<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>the categories of personal information that we collect;<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>the purposes for which the collected personal information is used;<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>whether we sell or share personal information to third parties;<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">5.</span>the categories of personal information that we sold, shared, or disclosed for a business purpose;<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">6.</span>the categories of third parties to whom the personal information was sold, shared, or disclosed for a business purpose;<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">7.</span>the business or commercial purpose for collecting, sharing, or selling personal information; and<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">8.</span>the specific pieces of personal information we collected about you.<br /><br /><br />
            In accordance with applicable law, we are not obligated to provide or delete consumer information that is de-identified in response to a consumer request or to re-identify individual data to verify a consumer request.<br /><br /><br />
            Right to Non-Discrimination for the Exercise of a Consumer’s Privacy Rights<br /><br /><br />
            We will not discriminate against you if you exercise your privacy rights.<br /><br /><br />
            Right to Limit Use and Disclosure of Sensitive Personal Information<br /><br /><br />
            We do not process consumer’s sensitive personal information.<br /><br /><br />
            Verification process<br /><br /><br />
            Upon receiving your request, we will need to verify your identity to determine you are the same person about whom we have the information in our system. These verification efforts require us to ask you to provide information so that we can match it with information you have previously provided us. For instance, depending on the type of request you submit, we may ask you to provide certain information so that we can match the information you provide with the information we already have on file, or we may contact you through a communication method (e.g., phone or email) that you have previously provided to us. We may also use other verification methods as the circumstances dictate.<br /><br /><br />
            We will only use personal information provided in your request to verify your identity or authority to make the request. To the extent possible, we will avoid requesting additional information from you for the purposes of verification. However, if we cannot verify your identity from the information already maintained by us, we may request that you provide additional information for the purposes of verifying your identity and for security or fraud-prevention purposes. We will delete such additionally provided information as soon as we finish verifying you.<br /><br /><br />
            Other privacy rights<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>You may object to the processing of your personal information.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>You may request correction of your personal data if it is incorrect or no longer relevant, or ask to restrict the processing of the information.<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>You can designate an authorized agent to make a request under the CCPA on your behalf. We may deny a request from an authorized agent that does not submit proof that they have been validly authorized to act on your behalf in accordance with the CCPA.<br /><br /><br />
            To exercise these rights, you can contact us by email at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link> or by referring to the contact details at the bottom of this document. If you have a complaint about how we handle your data, we would like to hear from you.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Financial Incentives</span><br /><br /><br />
            “Financial incentive” means a program, benefit, or other offering, including payments to consumers as compensation, for the disclosure, deletion, sharing, or sale of personal information.<br /><br /><br />
            The law permits financial incentives or a price or service difference if it is reasonably related to the value of the consumer’s data. A business must be able to explain how the financial incentive or price or service difference is reasonably related to the value of the consumer’s data. The explanation must include:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>a good-faith estimate of the value of the consumer’s data that forms the basis for offering the financial incentive or price or service difference; and<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>a description of the method the business used to calculate the value of the consumer’s data.<br /><br /><br />
            We may decide to offer a financial incentive (e.g., price or service difference) in exchange for the retention, sale or sharing of a consumer’s personal information.<br /><br /><br />
            If we decide to offer a financial incentive, we will notify you of such financial incentive and explain the price difference, as well as material terms of the financial incentive or price of service difference, including the categories of personal information that are implicated by the financial incentive or price or service difference.<br /><br /><br />
            If you choose to participate in the financial incentive you can withdraw from the financial incentive at any time by emailing us at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link> or by referring to the contact details at the bottom of this document.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Metrics</span><br /><br /><br />
            Our metrics for all CCPA requests received for the previous calendar year<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">15. DO VIRGINIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>Yes, if you are a resident of Virginia, you may be granted specific rights regarding access to and use of your personal information.<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">Virginia CDPA Privacy Notice</span><br /><br /><br />
            Under the Virginia Consumer Data Protection Act (CDPA):<br /><br /><br />
            “Consumer” means a natural person who is a resident of the Commonwealth acting only in an individual or household context. It does not include a natural person acting in a commercial or employment context.<br /><br /><br />
            “Personal data” means any information that is linked or reasonably linkable to an identified or identifiable natural person. “Personal data” does not include de-identified data or publicly available information.<br /><br /><br />
            “Sale of personal data” means the exchange of personal data for monetary consideration.<br /><br /><br />
            If this definition of “consumer” applies to you, we must adhere to certain rights and obligations regarding your personal data.<br /><br /><br />
            The information we collect, use, and disclose about you will vary depending on how you interact with <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> and our Services. To find out more, please visit the following sections above:<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>WHAT INFORMATION DO WE COLLECT?<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>HOW DO WE PROCESS YOUR INFORMATION?<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?<br /><br /><br />
            Your rights with respect to your personal data<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">1.</span>Right to be informed whether or not we are processing your personal data<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">2.</span>Right to access your personal data<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">3.</span>Right to correct inaccuracies in your personal data<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">4.</span>Right to request deletion of your personal data<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">5.</span>Right to obtain a copy of the personal data you previously shared with us<br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">6.</span>Right to opt out of the processing of your personal data if it is used for targeted advertising, the sale of personal data, or profiling in furtherance of decisions that produce legal or similarly significant effects<br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> has not sold any personal data to third parties for business or commercial purposes. <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span> will not sell personal data in the future belonging to website visitors, users, and other consumers.<br /><br /><br />
            Exercise your rights provided under the Virginia CDPA<br /><br /><br />
            More information about our data collection and sharing practices can be found in this privacy notice<br /><br /><br />
            You can opt out from the selling of your personal data, targeted advertising, or profiling by disabling cookies in Cookie Preference Settings.<br /><br /><br />
            You may contact us by email at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link> or by referring to the contact details at the bottom of this document.<br /><br /><br />
            If you are using an authorized agent to exercise your rights, we may deny a request if the authorized agent does not submit proof that they have been validly authorized to act on your behalf.<br /><br /><br />
            Verification process<br /><br /><br />
            We may request that you provide additional information reasonably necessary to verify you and your consumer’s request. If you submit the request through an authorized agent, we may need to collect additional information to verify your identity before processing your request.<br /><br /><br />
            Upon receiving your request, we will respond without undue delay, but in all cases, within forty-five (45) days of receipt. The response period may be extended once by forty-five (45) additional days when reasonably necessary. We will inform you of any such extension within the initial 45-day response period, together with the reason for the extension.<br /><br /><br />
            Right to appeal<br /><br /><br />
            If we decline to take action regarding your request, we will inform you of our decision and reasoning behind it. If you wish to appeal our decision, please email us at <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>. Within sixty (60) days of receipt of an appeal, we will inform you in writing of any action taken or not taken in response to the appeal, including a written explanation of the reasons for the decisions.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">16. DO WE MAKE UPDATES TO THIS NOTICE?</span><br /><br /><br />
            <span className="text-xl md:text-2xl font-sans font-bold text-white">In Short: </span>Yes, we will update this notice as necessary to stay compliant with relevant laws.<br /><br /><br />
            We may update this privacy notice from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">17. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span><br /><br /><br />
            If you have questions or comments about this notice, you may contact by email at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link> If you are a resident in the European Economic Area, the “data controller” of your personal information is <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>.<br /><br /><br />
            If you are a resident in the United Kingdom, the “data controller” of your personal information is <span className="text-xl md:text-2xl font-sans font-bold text-white">SaghiOMey</span>.<br /><br /><br />
            You can contact them directly regarding the processing of your information by email at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link>.<br /><br /><br />
            <span className="text-2xl md:text-4xl font-sans font-bold text-white">18. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</span><br /><br /><br />
            Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please contact us by email at <Link href="https://saghiomey.netlify.app/Contact" className="text-blue-900">Contact Us</Link>.<br /><br /><br />
            </span>
          </div>
          <Footer lastepisode = {lastepisode} />
        </div>
      </div>
    </>
  );
}
